// This contains code generated by ChatGPT, I do NOT want to have to rely on ChatGPT so I will only be using this as a referencing point I suppose.

const { SlashCommandBuilder } = require("discord.js");

module.exports = {
    data: new SlashCommandBuilder()
        .setName('ping')
        .setDescription('Simple ping command!'),
        
    async execute(interaction) {
        await interaction.reply({ content: "Pong!", ephemeral: true });
    }
};
